name: NodeJS GitHub action example

on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    container: node:12
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: npm run-script test
