name: Node.js CI

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm i
      - run: npm run-script test
  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - run: npm run-script test